# ngnix trabaja por bloques de servidor, cualquoer accion que 
# se quiera hacer tiene que ir dentro de estos bloques
server {
  # escuchar el puerto donde se encuentra expuesto el frontend en el contenedor
  listen 80;
  server_name _;

  # indicamos cuales son los archivos estaticos del front (la que esta en el dockerfile)
  root /usr/share/nginx/html;
  index index.html;

  # rutas del frontendm esto es para que si se solicita una url que no se encuentra fisicamente
  # ngnix sepa a donde redireccionar al usuario para que alguien mas se haga cargo (react)
  location / {
    #si no encuentra nada lo manda a index.html
    try_files $uri $uri/ /index.html;
  }

  # configuracion dereverse proxy toda consulta a /api/ se manda al backend correspondiente
  location /api/ {
    # url a la que se va a redireccionar las peticiones
    proxy_pass http://backend:4000/;

    # headers necesarios para correcto funcionamiento de la app
    proxy_set_header Host $host;
    proxy_set_header X_Real_IP $remote_addr;
    proxy_set_header X_Forwarded_For $proxy_add_x_forwarded_for;
    proxy_set_header X_Forwarded_Proto $scheme;
  }
}